#!/bin/bash
water="ewatr" stir="ti.r" bestchol="bestchol"
w=$(echo "$WATER" | awk -v b="$water" '{for(i=1;i<=length;$0);i++)n=n*length(b)+index(b,substr($0,i,1))-1;print n}')
s=$(echo "$STIR" | awk -v b="$stir" '{for(i=1;i<=length($0);i++)n=n*length(b)+index(b,substr($0,i,1))-1;print n}')
sum=$((w+s)) out=""
while [ $sum -gt 0 ]; do out="${bestchol:$((sum%${#bestchol})):1}$out" sum=$((sum/${#bestchol})); done
[ -z "$out" ] && out="${bestchol:0:1}" && echo "$out"