#!/bin/bash
awk 'function todec(s,b){n=0;for(i=1;i<=length(s);i++)n=n*length(b)+index(b,substr(s,i,1))-1;return n}{w=todec(ENVIRON["WATER"],"water");s=todec(ENVIRON["STIR"],"stir");n=w+s;b="bestchol";o="";do{o=substr(b,(n%length(b))+1,1)o;n=int(n/length(b))}while(n>0);print o}'
